### ISSUE TITLE
can't pull notebooks

### ISSUE THREAD

**Issue by navtis** [vinaygoel/ars-workshop#8]
Following the Readme I get the following error (consistently). I'm not used to docker. Any suggestions?
Thanks

`latest: Pulling from vinaygoel/ars-docker-notebooks
5c90d4a2d1a8: Pull complete 
c0a155833582: Pull complete 
f6c01ee70`2d1: Downloading 157.8 MB/477.1 MB
9d2a446002f1: Download complete 
715f90fabb7f: Download complete 
c957ca35c6ea: Downloading 102.2 MB/282 MB
2bcec55883e0: Downloading 
75f4603667e3:Waiting 
38927eb7094f: Waiting 
37565ca8a881: Waiting 
5fa0ff6f6612: Waiting 
efb1c4c5eb1c: Waiting 
c272c2b9d4af: Waiting 
docker: unauthorized: authentication required.`

**Comment by machawk1** [comment]
@ibnesayeed?

**Comment by ibnesayeed** [comment]
@navtis, I am not sure which layer is private that is seeking authorization, but here are a few things you can try.

If you have a [DockerHub](https://hub.docker.com/) account (consider creating if you don't have one already), try to login from your terminal so that your access credentials are saved under `~/.docker/config.json` which will then be used when authentication is required.

```
$ docker login
```

Above command will take care of crating that file, if not already populated. Then you can try pulling the image as usual.

```
$ docker pull vinaygoel/ars-docker-notebooks
```

Alternatively, you can build the image yourself, rather than downloading it from the hub. Please follow the steps below:

```
$ cd /tmp
$ git clone https://github.com/vinaygoel/ars-docker-notebooks.git
$ cd ars-docker-notebooks
$ docker build -t vinaygoel/ars-docker-notebooks .
```

Hope, it helps!

**Comment by navtis** [comment]
Thanks @ibnsayeed. Although I have a docker account and ~/.docker/config.json appears ok, that didn't help. But building the image directly worked fine and the exercises now run OK.

**Comment by vinaygoel** [comment]
Thanks for commenting while I was away @ibnsayeed :)
